project:
  type: website
  output-dir: docs


website:
  title: "David Rios"
  favicon: "Hermo.jpeg"
  google-analytics: G-JBCLMNEM0Z
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Résumé
      - href: projects.qmd
        text: Projects
      - icon: linkedin
        href: https://www.linkedin.com/in/hermogenesdavid/ 
      - icon: envelope
        href: mailto:hriostor@macalester.edu 

  page-footer:
      left: |
        &copy; David Rios, 2025<br>
        All content licensed under <i class='bi-badge-cc'></i>
        [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      right: |
        Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true




editor: visual


